version: "3.8"
services:
  consul:
    image: hashicorp/consul:1.11.3
    container_name: consul-server1
    ports:
      - '8501:8501'
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8600:8600'
      - '8600:8600/udp'
    healthcheck:
      test: >-
        curl -ks https://localhost:8501/v1/health/node/consul-server1
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - ./server1.json:/consul/config/server1.json:ro
      - ./certs/:/consul/config/certs/:ro
